{
  imports = [
    ./foot.nix
    ./anyrun.nix
    ./gammastep.nix
    ./firefox.nix
    ./mpv.nix
    ./qimgv.nix
    ./obsidian.nix
    ./thunderbird.nix
    ./vesktop.nix
    ./waybar.nix
    ./quickshell
    ./obs-studio.nix
    ./easyeffects.nix
    ./spicetify.nix
    ./davinci-resolve.nix
    ./minecraft.nix
    ./unity.nix
    ./rider.nix
  ];
}
